"""empty message

Revision ID: fbe576396efb
Revises: 
Create Date: 2025-07-14 16:51:19.811514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe576396efb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurar_codigos_password',
    sa.Column('codigo_uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fecha_expedicion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_usuario', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre_de_usuario')
    )
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=25), nullable=False),
    sa.Column('caracteristicas', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('nuevo', 'como_nuevo', 'bueno', 'regular', 'malo', name='estado_enum'), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('electronica', 'ropa', 'hogar', 'deportes', 'libros', 'juguetes', 'otros', name='categoria_enum'), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datos_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('codigo_postal', sa.String(length=50), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulo_favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('es_favorito', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion_trueke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_transaccion', sa.Enum('aceptado', 'terminado', 'pendiente', name='estado_transaccion_enum'), nullable=False),
    sa.Column('articulo_propietario_id', sa.Integer(), nullable=False),
    sa.Column('articulo_receptor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_propietario_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['articulo_receptor_id'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transaccion_trueke.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('trueke_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntuacion >= 1 AND puntuacion <= 5', name='check_puntuacion_rango'),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['trueke_id'], ['transaccion_trueke.id'], ),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comentario')
    op.drop_table('transaccion_trueke')
    op.drop_table('articulo_favorito')
    op.drop_table('datos_personales')
    op.drop_table('articulo')
    op.drop_table('usuario')
    op.drop_table('restaurar_codigos_password')
    # ### end Alembic commands ###
